create TABLE IF NOT EXISTS user (id INTEGER PRIMARY KEY AUTO_INCREMENT, username varchar(20) UNIQUE NOT NULL, password varchar(500) NOT NULL);
create TABLE IF NOT EXISTS post (id INTEGER PRIMARY KEY AUTO_INCREMENT,author_id INTEGER NOT NULL,created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,title TEXT NOT NULL,body TEXT NOT NULL,FOREIGN KEY (author_id) REFERENCES user (id));
